# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-19 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intelligence_result_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intelligence_id', models.CharField(max_length=255)),
                ('event_id', models.CharField(max_length=255)),
                ('links', models.CharField(max_length=1024)),
                ('type', models.IntegerField(max_length=3)),
                ('operate_time', models.IntegerField(max_length=10)),
                ('operate_uid', models.IntegerField(max_length=20)),
                ('create_time', models.IntegerField(max_length=10)),
                ('update_time', models.IntegerField(max_length=10)),
                ('is_deleted', models.IntegerField(max_length=3)),
                ('open_links', models.CharField(max_length=1296)),
                ('operate_type', models.IntegerField(max_length=3)),
                ('road_name', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
                ('remind', models.CharField(max_length=255)),
                ('COMMENT', models.CharField(max_length=255)),
                ('event_geo', models.CharField(max_length=255)),
                ('start_time', models.IntegerField(max_length=10)),
                ('end_time', models.IntegerField(max_length=10)),
                ('weekdays', models.CharField(max_length=255)),
                ('pace_ride_limit', models.CharField(max_length=255)),
                ('start_hour', models.IntegerField(max_length=10)),
                ('end_hour', models.IntegerField(max_length=10)),
                ('event_type', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'intelligence_result_log',
            },
        ),
    ]
