# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-20 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sys_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bd_uid', models.IntegerField(max_length=20)),
                ('bd_uname', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(max_length=4)),
                ('company_id', models.IntegerField(max_length=20)),
                ('user_desc', models.CharField(max_length=255)),
                ('create_user_id', models.IntegerField(max_length=20)),
                ('last_operator_id', models.IntegerField(max_length=20)),
                ('create_time', models.IntegerField(max_length=10)),
                ('update_time', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
    ]
